<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Team Colors
    |--------------------------------------------------------------------------
    | Keyed by the constructor `name` as returned by the Jolpica/Ergast API.
    | Value is the primary hex color used to theme driver/constructor cards.
    | Fallback (when a team isn't listed) is `default_team_color`.
    */

    'default_team_color' => '#E5E7EB',

    'team_colors' => [
        // Current grid
        'Red Bull'          => '#4781D7',
        'Ferrari'           => '#ED1131',
        'Mercedes'          => '#00D7B6',
        'McLaren'           => '#F47600',
        'Alpine F1 Team'    => '#00A1E8',
        'Aston Martin'      => '#229971',
        'Williams'          => '#1868DB',
        'RB F1 Team'        => '#6C98FF',
        'Sauber'            => '#01C00E',
        'Haas F1 Team'      => '#9C9FA2',

        // Recent / 2010s – 2020s
        'AlphaTauri'        => '#2B4562',
        'Alfa Romeo'        => '#900000',
        'Racing Point'      => '#F596C8',
        'Force India'       => '#F596C8',
        'Toro Rosso'        => '#469BFF',
        'Renault'           => '#FFF500',
        'Lotus F1'          => '#FFB800',
        'Caterham'          => '#0A6E31',
        'Marussia'          => '#6E0000',
        'Manor Marussia'    => '#6E0000',
        'Virgin'            => '#CC0000',
        'HRT'               => '#B2945E',
        'Brawn'             => '#BFD447',
        'BMW Sauber'        => '#1E41A8',
        'Honda'             => '#DC0000',
        'Super Aguri'       => '#B70000',
        'Toyota'            => '#CC0000',
        'Spyker'            => '#FF6700',
        'Spyker MF1'        => '#FF6700',
        'MF1'               => '#DC0000',
        'Midland'           => '#DC0000',
        'BAR'               => '#B40000',
        'Jaguar'            => '#004B31',
        'Minardi'           => '#1C1C1C',
        'Prost'             => '#00318F',
        'Stewart'           => '#FFFFFF',
        'Arrows'            => '#FB7504',

        // Classic / 80s – 90s
        'Tyrrell'           => '#003B7B',
        'Benetton'          => '#00A551',
        'Jordan'            => '#FFF500',
        'Forti'             => '#FFD700',
        'Ligier'            => '#0050A0',
        'Footwork'          => '#DC0000',
        'Lola'              => '#008000',
        'Pacific'           => '#A80000',
        'Simtek'            => '#1E1E1E',
        'Larrousse'         => '#0050B5',
        'Leyton House'      => '#2EC4B6',
        'March'             => '#E50000',
        'Rial'              => '#808080',
        'EuroBrun'          => '#1C1C1C',
        'Zakspeed'          => '#FFD700',
        'AGS'               => '#D0C7C5',
        'Osella'            => '#D0C7C5',
        'Coloni'            => '#FFC72C',
        'ATS'               => '#FFD700',
        'RAM'               => '#333333',
        'Toleman'           => '#8B0000',
        'Fondmetal'         => '#006400',
        'Dallara'           => '#1C1C1C',
        'Onyx'              => '#6E6E6E',
        'Life'              => '#C0C0C0',

        // 70s
        'Theodore'          => '#1C1C1C',
        'Fittipaldi'        => '#FFD700',
        'Copersucar'        => '#8B0000',
        'Ensign'            => '#003B7B',
        'Hesketh'           => '#1C1C1C',
        'Shadow'            => '#1C1C1C',
        'Wolf'              => '#003B7B',
        'Surtees'           => '#DC0000',
        'Penske'            => '#EFEFEF',
        'Hill'              => '#4169E1',
        'Embassy Hill'      => '#4169E1',
        'Eifelland'         => '#FFFFFF',
        'Tecno'             => '#DC0000',
        'Iso Marlboro'      => '#DC0000',
        'Parnelli'          => '#FFD700',
        'Politoys'          => '#FFFFFF',
        'Token'             => '#FFFFFF',
        'Trojan'            => '#FFFFFF',
        'Amon'              => '#000000',
        'Maki'              => '#FFD700',
        'Kojima'            => '#FFFFFF',
        'Martini'           => '#FFFFFF',

        // 60s
        'BRM'               => '#006400',
        'Matra'             => '#0050A0',
        'Matra-Ford'        => '#0050A0',
        'Eagle'             => '#003B7B',
        'Cooper'            => '#006400',
        'Cooper-Maserati'   => '#006400',
        'Honda RA'          => '#DC0000',
        'Porsche'           => '#C0C0C0',
        'BRP'               => '#006400',
        'Emeryson'          => '#006400',
        'De Tomaso'         => '#0050A0',
        'JBW'               => '#006400',
        'Scirocco'          => '#003B7B',
        'Brabham'           => '#0050A0',
        'Lotus'             => '#FFB800',
        'Team Lotus'        => '#FFB800',

        // 50s
        'Maserati'          => '#DC0000',
        'Talbot-Lago'       => '#0050A0',
        'Alta'              => '#006400',
        'Connaught'         => '#006400',
        'Gordini'           => '#0050A0',
        'HWM'               => '#006400',
        'Vanwall'           => '#006400',
        'Gilby'             => '#006400',
        'OSCA'              => '#DC0000',
        'Cisitalia'         => '#DC0000',
        'Stebro'            => '#FFFFFF',
        'Cisalpina'         => '#DC0000',
        'Veritas'           => '#C0C0C0',
        'AFM'               => '#C0C0C0',
        'EMW'               => '#C0C0C0',
        'BMW'               => '#1E41A8',
        'Simca-Gordini'     => '#0050A0',
        'Frazer Nash'       => '#006400',
        'ERA'               => '#006400',
        'Cegga'             => '#006400',
        'Ferguson'          => '#006400',
        'Lancia'            => '#DC0000',
        'Mercedes (1950s)'  => '#C0C0C0',

        // Indianapolis-era constructors (1950–60 Indy 500 counted toward WDC)
        'Kurtis Kraft'      => '#FFFFFF',
        'Epperly'           => '#FFFFFF',
        'Watson'            => '#FFFFFF',
        'Kuzma'             => '#FFFFFF',
        'Phillips'          => '#FFFFFF',
        'Trevis'            => '#FFFFFF',
        'Moore'             => '#FFFFFF',
        'Sutton'            => '#FFFFFF',
        'Lesovsky'          => '#FFFFFF',
        'Elder'             => '#FFFFFF',
        'Kurtis'            => '#FFFFFF',
        'Nichels'           => '#FFFFFF',
        'Christensen'       => '#FFFFFF',
        'Lascari'           => '#FFFFFF',
        'Pawl'              => '#FFFFFF',
        'Pankratz'          => '#FFFFFF',
        'Schroeder'         => '#FFFFFF',
        'Stevens'           => '#FFFFFF',
        'Langley'           => '#FFFFFF',
        'Deidt'             => '#FFFFFF',
        'Ewing'             => '#FFFFFF',
        'Dunn'              => '#FFFFFF',
        'Olson'             => '#FFFFFF',
        'Meskowski'         => '#FFFFFF',
        'Bromme'            => '#FFFFFF',
    ],

    /*
    |--------------------------------------------------------------------------
    | Nationality → Flag Code
    |--------------------------------------------------------------------------
    | Keyed by `driver.nationality` as returned by the Jolpica/Ergast API.
    | Value is the ISO 3166-1 alpha-2 code used by flagcdn.com.
    | Fallback (when a nationality isn't listed) is `default_flag_code`.
    */

    'default_flag_code' => 'xx',

    'nationality_flags' => [
        'American'        => 'us',
        'American-Italian'=> 'us',
        'Argentine'       => 'ar',
        'Argentine-Italian'=> 'ar',
        'Australian'      => 'au',
        'Austrian'        => 'at',
        'Belgian'         => 'be',
        'Brazilian'       => 'br',
        'British'         => 'gb',
        'Canadian'        => 'ca',
        'Chilean'         => 'cl',
        'Chinese'         => 'cn',
        'Colombian'       => 'co',
        'Czech'           => 'cz',
        'Czechoslovak'    => 'cz',
        'Danish'          => 'dk',
        'Dutch'           => 'nl',
        'East German'     => 'de',
        'English'         => 'gb',
        'Estonian'        => 'ee',
        'Filipino'        => 'ph',
        'Finnish'         => 'fi',
        'French'          => 'fr',
        'German'          => 'de',
        'Hungarian'       => 'hu',
        'Indian'          => 'in',
        'Indonesian'      => 'id',
        'Irish'           => 'ie',
        'Israeli'         => 'il',
        'Italian'         => 'it',
        'Japanese'        => 'jp',
        'Latvian'         => 'lv',
        'Liechtensteiner' => 'li',
        'Lithuanian'      => 'lt',
        'Malaysian'       => 'my',
        'Mexican'         => 'mx',
        'Monegasque'      => 'mc',
        'New Zealander'   => 'nz',
        'Polish'          => 'pl',
        'Portuguese'      => 'pt',
        'Rhodesian'       => 'zw',
        'Romanian'        => 'ro',
        'Russian'         => 'ru',
        'Saudi'           => 'sa',
        'Serbian'         => 'rs',
        'Slovak'          => 'sk',
        'Slovenian'       => 'si',
        'South African'   => 'za',
        'Spanish'         => 'es',
        'Swedish'         => 'se',
        'Swiss'           => 'ch',
        'Thai'            => 'th',
        'Turkish'         => 'tr',
        'Ukrainian'       => 'ua',
        'Uruguayan'       => 'uy',
        'Venezuelan'      => 've',
        'Yugoslav'        => 'rs',
    ],

];
